export const servicesMock = [
  {
    img: "https://cdn.pixabay.com/photo/2015/12/07/10/55/electric-1080584_1280.jpg",
    title: "Elétrica",
    subtitle:
      "Pinturas, Marcenaria, Carpintaria, Pedreiro, Ladrilheiro, Vidraceiro",
    slug: "eletrica",
    icon: "",
    services: [
      "Quadro de distribuição (instalação completa desde o início)",
      "Disjuntores",
      "Tomadas",
      "Interruptores",
      "IDR / DR",
      "Dimer",
      "Campainha",
      "Chuveiro (Instalação e Troca), troca de resistência, fiação.",
      "Lâmpada, luminária, croica, LED, barra de LED, lustres, arandelas, abajur.",
      "Fiação (adequação e troca)",
      "Fiação para TV/rede",
      "Fechadura eletrônica",
    ],
    images: [
      "https://cdn.pixabay.com/photo/2015/12/07/10/55/electric-1080584_1280.jpg",
      "https://www.picclickimg.com/6zkAAOSwN8plZOAl/Aigostar-Lampada-Da-Soffitto-LED-Bagno-18W-Equivalente.webp",
    ],
  },
  {
    img: "https://cdn.pixabay.com/photo/2018/08/10/18/03/bad-3597350_1280.jpg",
    title: "Hidráulica",
    subtitle: "Elétrica em Geral do Lar e de Empresas!",
    slug: "hidraulica",
    icon: "",
    services: [
      "Registro (Instalação, Manutenção, Vazamento, Troca)",
      "Chuveiro - instalação",
      "Pia/lavatório (troca de válvula, sifão, vedação com.silicone ou PU, tira vazamento)",
      "Torneira (instalação, troca de reparo, tira vazamento)",
      "Instalação de filtro e ou purificador, máquinas de lavar roupa, máquina de lavar louça)",
      "Instalação hidráulica desde o início",
    ],
    images: [
      "https://cdn.pixabay.com/photo/2018/08/10/18/03/bad-3597350_1280.jpg",
      "https://eletricista24hs.com.br/wp-content/uploads/2023/02/Instalacao-de-chuveiro.png",
      "https://blog.casadastorneiras.com.br/wp-content/uploads/2022/02/torneira-vazando-thumb.jpg",
    ],
  },
  {
    img: "https://cdn.pixabay.com/photo/2017/02/24/12/24/bathroom-2094733_1280.jpg",
    title: "Esgoto",
    subtitle:
      "Cortinas, Persianas, Corrimãos, Cantoneiras, Quadros, Rodapés, Fechadura eletrônica, Lustres, Etc",
    slug: "esgoto",
    icon: "",
    services: [
      "Instalação de vaso sanitário",
      "Instalação de caixa de descarga",
      "Manutenção e reparos em caixa acoplada",
      "Limpeza de ralos sifão",
      "Desentupimento",
    ],
    images: [
      "https://cdn.pixabay.com/photo/2017/02/24/12/24/bathroom-2094733_1280.jpg",
      "https://sorodesentupidora.com.br/wp-content/uploads/2019/05/como-funciona-a-instalacao-de-vasos-sanitarios-min.png",
      "https://www.cleanipedia.com/images/00d1hxgfwfa6/6AThNqVUK9bQOT3ypnF53s/a6b9084412b78b78c0360c90b8ccb1b6/Q19waWFfZGVfQ19waWFfZGVfQ0xQXy1fTm92ZW1icm8wMV9fMTdfLmpwZw/1200w/como-limpar-ralo-de-banheiro.jpg",
    ],
  },
  {
    img: "https://cdn.pixabay.com/photo/2016/11/19/13/06/bed-1839183_1280.jpg",
    title: "Serviços Diversos",
    subtitle: "Montagem e desmontagem de móveis para o Lar e para empresas.",
    slug: "servicos-diversos",
    icon: "",
    services: [
      "Instalação de coifa/depurador",
      "Instalação de varal",
      "Desentupimento de fogão",
      "Limpeza de exaustor de banheiro",
      "Instalação de TV (parede, teto, painel)",
      "Instalação de corrimãos",
      "Instalação de cortinas/persianas",
      "Instalação de barra de apoio ou sustentação",
      "Instalação de quadros, relógios, santuário, cascatas,. cantoneiras",
    ],
    images: [
      "https://cdn.pixabay.com/photo/2016/11/19/13/06/bed-1839183_1280.jpg",
      "https://s2-techtudo.glbimg.com/tC9uKY7Y26eQlRuT7MiYIs2U3Uo=/0x0:1000x764/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2019/5/a/VPsdJcQBAVfMVqxgOdag/0.veja-o-que-voce-precisa-saber-antes-de-comprar-e-instalar-um-suporte-de-parede-para-tv.jpg",
    ],
  },
  {
    img: "https://www.quemconserta.com/wp-content/uploads/2023/06/Captura-de-Tela-2023-04-23-as-11.21.28.png",
    title: "Marcenaria",
    subtitle: "Desmontagem, Encaixotamento, Transporte, Montagem",
    slug: "marcenaria",
    icon: "",
    services: [
      "Instalação/montagem: rack, painel, mesa, sofá, estantes, prateleira, guarda roupa, cadeiras",
      "Ajustes em portas",
      "Troca de dobradiças, pistões, puxadores ",
      "Instalação de olho mágico",
    ],
    images: [
      "https://www.quemconserta.com/wp-content/uploads/2023/06/Captura-de-Tela-2023-04-23-as-11.21.28.png",
      "https://s2-casaejardim.glbimg.com/IlhpUAqSvcMuTqqFCxtB7NlG170=/0x0:1957x1532/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_a0b7e59562ef42049f4e191fe476fe7d/internal_photos/bs/2022/r/Q/d5oRXGRPyJAY8anZwhlA/2022-06-17-gettyimages-614738828.jpeg",
    ],
  },
  {
    img: "https://m.media-amazon.com/images/I/518YohP2hxL._AC_.jpg",
    title: "Fibra Sintética",
    subtitle: "Fabricação e Reformas de Móveis de Fibra Sintética",
    slug: "fibra-sintetica",
    icon: "",
    services: ["Fabricação', 'Reforma"],
    images: [
      "https://m.media-amazon.com/images/I/518YohP2hxL._AC_.jpg",
      "https://painel.homeelazer.com.br/painel/imagens/blog/1687279936-20230616_fotos_blog_redimensionadas_2.jpg",
      "https://images.tcdn.com.br/img/img_prod/1134346/conjunto_de_sofa_fibra_sintetica_bola_1_sofa_2_l_2_poltronas_1_mesa_centro_tecido_linum_2033_1_dc3d3a904fa5f3855711eedb0fa4ed54.jpeg",
    ],
  },
  {
    img: "https://engenharia360.com/wp-content/uploads/2022/03/Chale-de-Madeira-1024x683.webp",
    title: "Pintura",
    subtitle: "Fabricação e Reformas de Móveis de Fibra Pintura",
    slug: "pintura",
    icon: "",
    services: [
      "Pintura em geral",
      "Verniz em móveis, porta e alisar",
      "Madeiramento externo e telhado",
    ],
    images: [
      "https://cdn.pixabay.com/photo/2021/07/24/21/51/brush-6490441_1280.jpg",
      "https://img.freepik.com/fotos-premium/pintura-de-parede-vermelha-no-quarto-apos-a-restauracao-ou-reforma_157125-7185.jpg?w=900",
      "https://img.freepik.com/fotos-premium/renovacao-e-modernizacao-com-paredes-de-drywall-achatadas_157125-7183.jpg?w=900",
      "https://engenharia360.com/wp-content/uploads/2022/03/Chale-de-Madeira-1024x683.webp",
    ],
  },
  {
    img: "https://img.freepik.com/fotos-premium/instalacao-de-macaneta-com-trava-para-porta-interna_351981-155.jpg",
    title: "Carpintaria",
    subtitle: "Fabricação e Reformas de Móveis de Fibra Sintética",
    slug: "carpintaria",
    icon: "",
    services: [
      "Instalação, Assentamento, Manutenção e Ajuste em Porta e Alisar.",
      "Instalação de fechadura e maçaneta",
    ],
    images: [
      "https://www.cec.com.br/files/blog/posts/2020/11_novembro/20201125/Fechadura-700x409_2.png",
      "https://img.freepik.com/fotos-premium/instalacao-de-macaneta-com-trava-para-porta-interna_351981-155.jpg",
    ],
  },
  {
    img: "https://www.repasso.com.br/wp-content/uploads/2016/02/674489.jpg",
    title: "Pedreiro/Ladrilheiro",
    subtitle: "Fabricação e Reformas de Móveis de Fibra Sintética",
    slug: "pedreiro-ladrilheiro",
    icon: "",
    services: ["Todo tipo de serviço do segmento"],
    images: [
      "https://www.repasso.com.br/wp-content/uploads/2016/02/674489.jpg",
      "https://servicos.nainternet17.com.br/wp-content/uploads/2018/01/ladrilheiro-rj-300x214.png",
      "https://cliquesobradinho.com.br/media/cache/small/custom/domain_1/image_files/sitemgr_photo_795.jpg",
    ],
  },
  {
    img: "https://www.ccvvidros.com.br/box-de-vidro/imagens/box-de-vidro-para-banheiro-preco.jpg",
    title: "Vidraceiro",
    subtitle: "Fabricação e Reformas de Móveis de Fibra Sintética",
    slug: "vidraceiro",
    icon: "",
    services: [
      "Instalação de box, espelho",
      "Vedação e manutenção box e fachadas",
      "Blindex para divisão de ambiente",
    ],
    images: [
      "https://www.vidrosquitauna.com.br/boxvidro/big/(69).jpg",
      "https://www.vidracariaaguabranca.com.br/wp-content/uploads/2021/10/Diferenca-entre-Blindex-e-vidro-temperado.webp",
      "https://www.ccvvidros.com.br/box-de-vidro/imagens/box-de-vidro-para-banheiro-preco.jpg",
    ],
  },
  {
    img: "https://fellizardo.com.br/wp-content/uploads/2020/09/Montador-de-moveis-santo-andre.jpg",
    title: "Moveis",
    subtitle: "Fabricação e Reformas de Móveis de Fibra Sintética",
    slug: "moveis",
    icon: "",
    services: ["Montagem", "Desmontagem"],
    images: [
      "https://fellizardo.com.br/wp-content/uploads/2020/09/Montador-de-moveis-santo-andre.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQ867spu48PmDyqrZNgEE-VRQzCGXBmr_KInt-96sXRJlYrcFqR33Y_qcl_BRinDHhy80&usqp=CAU",
      "https://www.orcamentomudancasonline.com/assets/site/upload/1574941576.png",
    ],
  },
  {
    img: "https://www.shutterstock.com/image-photo/inside-removal-van-showing-fabric-600nw-2272242425.jpg",
    title: "Mudança",
    subtitle: "Fabricação e Reformas de Móveis de Fibra Sintética",
    slug: "mudanca",
    icon: "",
    services: ["Desmontagem", "Encaixotamento", "Transporte", "Montagem"],
    images: [
      "https://www.shutterstock.com/image-photo/inside-removal-van-showing-fabric-600nw-2272242425.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzFeTWEtWaTXGaVU1ENjJWPFasqPYk5kgPfw&usqp=CAU",
      "https://infinityimobiliaria.com.br/wp-content/uploads/2022/02/mudanca-de-casa_blog.jpg",
    ],
  },
];
